Results of doctest builder run on 2024-02-07 11:54:02
=====================================================

Document: usage
---------------
**********************************************************************
File "usage.rst", line 67, in default
Failed example:
    Results = ISARA.Retr_CRI(wvl,measured_sca_coef,measured_abs_coef,sd1,sd2,dpg1,dpg2,CRI,size_equ1,size_equ2,nonabs_fraction1,nonabs_fraction2,shape1,shape2,rho1,rho2,num_theta)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[24]>", line 1, in <module>
        Results = ISARA.Retr_CRI(wvl,measured_sca_coef,measured_abs_coef,sd1,sd2,dpg1,dpg2,CRI,size_equ1,size_equ2,nonabs_fraction1,nonabs_fraction2,shape1,shape2,rho1,rho2,num_theta)
      File "/home/jsschlosser/mopsmap/ISARA.py", line 100, in Retr_CRI
        results = mopsmap_wrapper.Model(wvl,size_equ,sd,dpg,RRI,IRI,nonabs_fraction,shape,rho,0,kappa,num_theta)
      File "/home/jsschlosser/mopsmap/mopsmap_wrapper.py", line 94, in Model
        p = subprocess.Popen([path_mopsmap_executable, f'{filename}.inp'], stdout = subprocess.PIPE, stderr = subprocess.STDOUT, close_fds = True)
      File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: './mopsmap'
**********************************************************************
File "usage.rst", line 106, in default
Failed example:
    Results = ISARA.Retr_CRI(wvl,measured_sca_coef,measured_abs_coef,sd1,sd2,dpg1,dpg2,CRI,size_equ1,size_equ2,nonabs_fraction1,nonabs_fraction2,shape1,shape2,rho1,rho2,num_theta)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[24]>", line 1, in <module>
        Results = ISARA.Retr_CRI(wvl,measured_sca_coef,measured_abs_coef,sd1,sd2,dpg1,dpg2,CRI,size_equ1,size_equ2,nonabs_fraction1,nonabs_fraction2,shape1,shape2,rho1,rho2,num_theta)
      File "/home/jsschlosser/mopsmap/ISARA.py", line 100, in Retr_CRI
        results = mopsmap_wrapper.Model(wvl,size_equ,sd,dpg,RRI,IRI,nonabs_fraction,shape,rho,0,kappa,num_theta)
      File "/home/jsschlosser/mopsmap/mopsmap_wrapper.py", line 94, in Model
        p = subprocess.Popen([path_mopsmap_executable, f'{filename}.inp'], stdout = subprocess.PIPE, stderr = subprocess.STDOUT, close_fds = True)
      File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: './mopsmap'
**********************************************************************
File "usage.rst", line 107, in default
Failed example:
    RRI_dry = Results["RRIdry"]
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[25]>", line 1, in <module>
        RRI_dry = Results["RRIdry"]
    NameError: name 'Results' is not defined
**********************************************************************
File "usage.rst", line 108, in default
Failed example:
    IRI_dry = Results["IRIdry"]
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[26]>", line 1, in <module>
        IRI_dry = Results["IRIdry"]
    NameError: name 'Results' is not defined
**********************************************************************
File "usage.rst", line 109, in default
Failed example:
    CRI1 = np.array([RRI_dry,IRI_dry])
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[27]>", line 1, in <module>
        CRI1 = np.array([RRI_dry,IRI_dry])
    NameError: name 'RRI_dry' is not defined
**********************************************************************
File "usage.rst", line 110, in default
Failed example:
    CRI2 = np.array([RRI_dry,IRI_dry])
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[28]>", line 1, in <module>
        CRI2 = np.array([RRI_dry,IRI_dry])
    NameError: name 'RRI_dry' is not defined
**********************************************************************
File "usage.rst", line 114, in default
Failed example:
    Results2 = ISARA.Retr_kappa(wvl,measured_sca_coef,measured_wet_sca_coef,sd1,sd2,dpg1,dpg2,RH,Kappa,CRI1,CRI2,size_equ1,size_equ2,nonabs_fraction1,nonabs_fraction2,shape1,shape2,rho1,rho2,num_theta)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[32]>", line 1, in <module>
        Results2 = ISARA.Retr_kappa(wvl,measured_sca_coef,measured_wet_sca_coef,sd1,sd2,dpg1,dpg2,RH,Kappa,CRI1,CRI2,size_equ1,size_equ2,nonabs_fraction1,nonabs_fraction2,shape1,shape2,rho1,rho2,num_theta)
    NameError: name 'CRI1' is not defined
**********************************************************************
File "../../importICARTT.py", line ?, in default
Failed example:
    output_dictionary = importICT.imp("activate-mrg1_hu25_20200214_R0.ict")
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[0]>", line 1, in <module>
        output_dictionary = importICT.imp("activate-mrg1_hu25_20200214_R0.ict")
    NameError: name 'importICT' is not defined
**********************************************************************
File "../../importICARTT.py", line ?, in default
Failed example:
    print(output_dictionary)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[1]>", line 1, in <module>
        print(output_dictionary)
    NameError: name 'output_dictionary' is not defined
**********************************************************************
File "../../ISARA_ACTIVATE_Data_Retrieval.py", line ?, in default
Failed example:
    ISARA_ACTIVATE_Data_Retrieval.RunISARA()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[1]>", line 1, in <module>
        ISARA_ACTIVATE_Data_Retrieval.RunISARA()
      File "/home/jsschlosser/mopsmap/ISARA_ACTIVATE_Data_Retrieval.py", line 100, in RunISARA
        dpg2 = load_sizebins.Load('LAS_bin_sizes.csv')*pow(10,-3)
      File "/home/jsschlosser/mopsmap/load_sizebins.py", line 15, in Load
        G = open(filename, 'r')  # open .csv
    FileNotFoundError: [Errno 2] No such file or directory: 'LAS_bin_sizes.csv'
**********************************************************************
1 items had failures:
  10 of  62 in default
62 tests in 1 items.
52 passed and 10 failed.
***Test Failed*** 10 failures.

Doctest summary
===============
   62 tests
   10 failures in tests
    0 failures in setup code
    0 failures in cleanup code
